version: '3'

services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - MYSQL_USER=rootdb
      - MYSQL_PASSWORD=root
    volumes:
      - /data/mysql
  spring-boot-manager:
    ##image: lucasvilela/stock-manager
    image: spring-boot-jpa-image
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
    ports:
      - 8081:8080

  networks:
    default:
      driver: stock-network
